SELECT * FROM dbo.NYPD_Arrest_Data_Year_to_Date;

--GET A TOTAL COUNT OF ARRESTS
SELECT COUNT(ARREST_KEY) AS TOTAL_ARRESTS 
FROM dbo.NYPD_Arrest_Data_Year_to_Date
WHERE ARREST_KEY IS NOT NULL;


--GET LOCATION COORDINATES
SELECT Latitude, Longitude 
FROM dbo.NYPD_Arrest_Data_Year_to_Date
WHERE Latitude IS NOT NULL AND Longitude IS NOT NULL

--GET AGE DISTRIBUTION
SELECT AGE_GROUP, COUNT(AGE_GROUP) AS AGE_DISTRIBUTION
FROM dbo.NYPD_Arrest_Data_Year_to_Date
WHERE AGE_GROUP IS NOT NULL
GROUP BY AGE_GROUP
ORDER BY AGE_GROUP ASC;

--GET RACE DISTRIBUTION
SELECT PERP_RACE, COUNT(PERP_RACE) AS RACE_DISTRIBUTION
FROM dbo.NYPD_Arrest_Data_Year_to_Date
WHERE PERP_RACE IS NOT NULL
GROUP BY PERP_RACE
ORDER BY PERP_RACE ASC;

--GET SEX DISTRIBUTION
SELECT PERP_SEX, COUNT(PERP_SEX) AS SEX_DISTRIBUTION
FROM dbo.NYPD_Arrest_Data_Year_to_Date
WHERE PERP_SEX IS NOT NULL
GROUP BY PERP_SEX
ORDER BY PERP_SEX ASC;

--GET ARREST FREQUENCY OVER TIME
SELECT OFNS_DESC, ARREST_DATE
FROM dbo.NYPD_Arrest_Data_Year_to_Date
WHERE ARREST_DATE IS NOT NULL
ORDER BY ARREST_DATE ASC;